# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(312, 449)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.labelBox = QtWidgets.QComboBox(self.centralwidget)
        self.labelBox.setObjectName("labelBox")
        self.gridLayout.addWidget(self.labelBox, 2, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setObjectName("addButton")
        self.gridLayout.addWidget(self.addButton, 13, 0, 1, 3)
        self.saveModel = QtWidgets.QPushButton(self.centralwidget)
        self.saveModel.setObjectName("saveModel")
        self.gridLayout.addWidget(self.saveModel, 12, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 11, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 11, 0, 1, 1)
        self.saveImage = QtWidgets.QPushButton(self.centralwidget)
        self.saveImage.setObjectName("saveImage")
        self.gridLayout.addWidget(self.saveImage, 10, 1, 1, 2)
        self.nameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.nameEdit.setText("")
        self.nameEdit.setObjectName("nameEdit")
        self.gridLayout.addWidget(self.nameEdit, 0, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 0, 1, 3)
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setText("")
        self.image.setObjectName("image")
        self.gridLayout.addWidget(self.image, 6, 1, 1, 1)
        self.label_2.raise_()
        self.label.raise_()
        self.saveModel.raise_()
        self.addButton.raise_()
        self.label_4.raise_()
        self.label_3.raise_()
        self.textBrowser.raise_()
        self.saveImage.raise_()
        self.labelBox.raise_()
        self.nameEdit.raise_()
        self.pushButton.raise_()
        self.image.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 312, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "添加模型地址"))
        self.label_2.setText(_translate("MainWindow", "模型标签"))
        self.addButton.setText(_translate("MainWindow", "确认"))
        self.saveModel.setText(_translate("MainWindow", "存入模型"))
        self.label.setText(_translate("MainWindow", "名称"))
        self.label_3.setText(_translate("MainWindow", "模型地址"))
        self.saveImage.setText(_translate("MainWindow", "存入图片"))
        self.label_4.setText(_translate("MainWindow", "效果图片"))
        self.pushButton.setText(_translate("MainWindow", "添加新标签"))
